version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/domainr/whois
    docker:
      - image: domainr/ci:swan
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v

      # Run tests
      - run: mkdir -p test-results
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report < test-results/go-test.log > test-results/go-test-report.xml" EXIT
            go test -v -race ./... | tee test-results/go-test.log

      # Report
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: results
