name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Go
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Vet Go code
        run: go vet ./...

      - name: Run Go tests
        run: go test -mod=readonly -v -race ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

  approve:
    name: Approve pull request
    needs: test
    if: startsWith(github.head_ref, 'dependabot/go_modules/github.com/zonedb/zonedb') # Only run on pull request
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DOMAINRBOT_RW_GITHUB_ACCESS_TOKEN }}
    steps:
      - run: gh pr review --approve ${{ github.head_ref }}

  # Via: https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-701889737
  # automerge:
  #   name: Automerge
  #   needs: test
  #   if: github.actor == 'dependabot[bot]'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Automerge
  #       uses: actions/github-script@v3
  #       with:
  #         github-token: ${{ secrets.DOMAINRBOT_RW_GITHUB_ACCESS_TOKEN }}
  #         script: |
  #           github.pulls.createReview({
  #             owner: context.payload.repository.owner.login,
  #             repo: context.payload.repository.name,
  #             pull_number: context.payload.pull_request.number,
  #             event: 'APPROVE'
  #           })
  #           github.pulls.merge({
  #             owner: context.payload.repository.owner.login,
  #             repo: context.payload.repository.name,
  #             pull_number: context.payload.pull_request.number
  #           })
